name: FamaFrench
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - idna=2.9
  - intel-openmp=2020.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - pip=20.0.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2020.1
  - readline=8.0
  - requests=2.23.0
  - setuptools=46.4.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - urllib3=1.25.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11

